# Generated by Django 2.2.6 on 2019-11-02 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name="nom de l'école")),
                ('degree', models.CharField(max_length=50, verbose_name='diplôme obtenu')),
                ('description2', tinymce.models.HTMLField(verbose_name='description')),
                ('entry_date', models.DateField(verbose_name="date d'entrée dans l'école")),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name="date de sortie de l'école")),
            ],
            options={
                'verbose_name': 'éducation',
                'verbose_name_plural': 'éducations',
                'ordering': ['entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50, verbose_name="nom de l'entreprise")),
                ('employment', models.CharField(max_length=100, verbose_name="type de l'emploi")),
                ('description', models.TextField(verbose_name="description de l'emploi")),
                ('entry_date', models.DateField(verbose_name="date d'arrivée dans l'entreprise")),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name="date de sortie de l'entreprise")),
            ],
            options={
                'verbose_name': 'expérience',
                'verbose_name_plural': 'expériences',
                'ordering': ['entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dev', models.BooleanField(default=False, verbose_name='est un développeur')),
                ('is_student', models.BooleanField(default=False, verbose_name='est un étudiant en informatique')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='est un formateur')),
                ('image', models.ImageField(default='user_pictures/default.png', upload_to='user_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])], verbose_name='image de profil')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='pays')),
                ('biography', models.TextField(blank=True, max_length=1500, null=True, verbose_name='biographie')),
                ('strike', models.PositiveSmallIntegerField(default=0, verbose_name='signalement')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='addresse e-mail confirmée')),
                ('email_notification', models.BooleanField(default=True, verbose_name='notification par email')),
                ('profile_reported', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='niveau')),
                ('level_experience', models.PositiveIntegerField(default=0, verbose_name='expérience acquise')),
                ('github_username', models.CharField(blank=True, max_length=100, null=True, verbose_name="nom d'utilisateur Github")),
                ('links', models.TextField(blank=True, default=';;;;;', null=True, verbose_name='liens vers les médias sociaux')),
            ],
            options={
                'verbose_name': 'profil',
                'ordering': ['-level', '-level_experience'],
            },
        ),
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('to_strike', models.BooleanField(default=False, verbose_name='à striker')),
                ('striked', models.BooleanField(default=False, verbose_name='striké')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.Profile', verbose_name='profil reporté')),
            ],
            options={
                'verbose_name': 'signalement de profil',
                'verbose_name_plural': 'signalements de profil',
            },
        ),
    ]
