# Generated by Django 2.2.3 on 2019-07-12 14:05

import accounts.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dev', models.BooleanField(default=False, verbose_name='Est un développeur')),
                ('is_student', models.BooleanField(default=False, verbose_name='Est un étudiant en informatique')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Est un formateur')),
                ('image', models.ImageField(default='user_pictures/default.png', upload_to='user_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])], verbose_name='Image de profil')),
                ('country', models.CharField(max_length=30)),
                ('biography', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Biographie')),
                ('strike', models.PositiveSmallIntegerField(default=0, verbose_name='Signalement')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Addresse e-mail confirmée')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Niveau')),
                ('level_experience', models.PositiveIntegerField(default=0, verbose_name='Expérience acquise')),
                ('favorite_articles', accounts.fields.StringListField(blank=True, default='', null=True, verbose_name='Articles favoris')),
                ('favorite_subjects', accounts.fields.StringListField(blank=True, default='', null=True, verbose_name='Sujets marqués comme favoris')),
                ('github_username', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom d'utilisateur/Email Github")),
                ('links', models.TextField(blank=True, null=True)),
                ('favorite_tutorials', models.ManyToManyField(blank=True, related_name='tutorial_favorite', to='courses.Tutorial', verbose_name='Tutoriels favoris')),
                ('languages_learnt', models.ManyToManyField(blank=True, to='main.Language', verbose_name='Langages maîtrisés')),
                ('tag_learnt', models.ManyToManyField(blank=True, to='main.Tag', verbose_name='Compétences apprises')),
                ('tutorial_finished', models.ManyToManyField(blank=True, related_name='tutorial_finished', to='courses.Tutorial', verbose_name='Tutoriels marqués comme terminé')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Profil',
                'ordering': ['-level', '-level_experience'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50, verbose_name="Nom de l'entreprise")),
                ('employment', models.CharField(max_length=250, verbose_name="Type d'emploi")),
                ('entry_date', models.DateField(verbose_name="Date d'entrée")),
                ('exit_date', models.DateField(verbose_name='Date de sortie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Expérience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name="Nom de l'école")),
                ('degree', models.CharField(max_length=50, verbose_name='Diplôme')),
                ('entry_date', models.DateField(verbose_name="Date d'entrée")),
                ('exit_date', models.DateField(verbose_name='Date de sortie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Éducation',
            },
        ),
    ]
