# Generated by Django 2.2.2 on 2019-06-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Langage'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag'},
        ),
    ]
