# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='article_favorite', to='articles.Article', verbose_name='articles favoris'),
        ),
    ]
