# Generated by Django 2.2.3 on 2019-07-05 16:19

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_tutorials',
            field=accounts.fields.StringListField(blank=True, default='', null=True, verbose_name='Tutoriels favoris'),
        ),
    ]
