# Generated by Django 2.2.2 on 2019-06-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Éducation'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Expérience'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user', 'level'], 'verbose_name': 'Profil'},
        ),
    ]
