# Generated by Django 2.2.2 on 2019-06-14 11:43

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190613_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoris',
            field=accounts.models.StringListField(default='', verbose_name='Articles favoris'),
        ),
    ]
