# Generated by Django 2.2.3 on 2019-07-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190713_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'éducation'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'expérience'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-level', '-level_experience'], 'verbose_name': 'profil'},
        ),
    ]
