# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('accounts', '0002_profile_favorite_articles'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, to='forum.Subject', verbose_name='sujets marqués comme favoris'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_tutorials',
            field=models.ManyToManyField(blank=True, related_name='tutorial_favorite', to='courses.Tutorial', verbose_name='tutoriels favoris'),
        ),
    ]
