# Generated by Django 2.2.2 on 2019-06-14 12:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_favoris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favoris',
            new_name='favorite_articles',
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Expérience acquise'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_subjects',
            field=accounts.models.StringListField(default='', verbose_name='Sujets marqués comme favoris'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Est un étudiant en informatique'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Niveau'),
        ),
    ]
