# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20191102_1828'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages_learnt',
            field=models.ManyToManyField(blank=True, to='main.Language', verbose_name='langages maîtrisés'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutorial_finished',
            field=models.ManyToManyField(blank=True, related_name='tutorial_finished', to='courses.Tutorial', verbose_name='tutoriels marqués comme terminé'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.Profile', verbose_name='profile associé'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.Profile', verbose_name='profile associé'),
        ),
    ]
