# Generated by Django 2.2.3 on 2019-08-01 09:51

import accounts.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190715_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50, verbose_name='diplôme'),
        ),
        migrations.AlterField(
            model_name='education',
            name='entry_date',
            field=models.DateField(verbose_name="date d'entrée"),
        ),
        migrations.AlterField(
            model_name='education',
            name='exit_date',
            field=models.DateField(verbose_name='date de sortie'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='profile associé'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=50, verbose_name="nom de l'école"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employment',
            field=models.CharField(max_length=250, verbose_name="type d'emploi"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(max_length=50, verbose_name="nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='entry_date',
            field=models.DateField(verbose_name="date d'entrée"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exit_date',
            field=models.DateField(verbose_name='date de sortie'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='profile associé'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='biographie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='addresse e-mail confirmée'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='article_favorite', to='articles.Article', verbose_name='articles favoris'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_subjects',
            field=accounts.fields.StringListField(blank=True, default='', null=True, verbose_name='sujets marqués comme favoris'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_tutorials',
            field=models.ManyToManyField(blank=True, related_name='tutorial_favorite', to='courses.Tutorial', verbose_name='tutoriels favoris'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="nom d'utilisateur/email Github"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_pictures/default.png', upload_to='user_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg'])], verbose_name='image de profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_dev',
            field=models.BooleanField(default=False, verbose_name='est un développeur'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='est un étudiant en informatique'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='est un formateur'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_learnt',
            field=models.ManyToManyField(blank=True, to='main.Language', verbose_name='langages maîtrisés'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='expérience acquise'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, null=True, verbose_name='liens vers les médias sociaux'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='strike',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='signalement'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag_learnt',
            field=models.ManyToManyField(blank=True, to='main.Tag', verbose_name='compétences apprises'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tutorial_finished',
            field=models.ManyToManyField(blank=True, related_name='tutorial_finished', to='courses.Tutorial', verbose_name='tutoriels marqués comme terminé'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé'),
        ),
    ]
