# Generated by Django 2.2.6 on 2019-12-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191102_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=1, verbose_name='ID du type')),
                ('profession_type', models.CharField(max_length=40, verbose_name='type de profession')),
                ('profession_type_fr', models.CharField(max_length=40, null=True, verbose_name='type de profession')),
                ('profession_type_en', models.CharField(max_length=40, null=True, verbose_name='type de profession')),
            ],
            options={
                'verbose_name': 'statut en programmation',
                'verbose_name_plural': 'statuts en programmation',
            },
        ),
    ]
