# Generated by Django 2.2.2 on 2019-06-14 14:34

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190614_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=accounts.models.StringListField(blank=True, default='', null=True, verbose_name='Compétences'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_articles',
            field=accounts.models.StringListField(blank=True, default='', null=True, verbose_name='Articles favoris'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_subjects',
            field=accounts.models.StringListField(blank=True, default='', null=True, verbose_name='Sujets marqués comme favoris'),
        ),
    ]
