# Generated by Django 2.2.3 on 2019-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190801_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='notification par email'),
        ),
    ]
