# Generated by Django 2.2.2 on 2019-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190614_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strike',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Signalement'),
        ),
    ]
