# Generated by Django 2.2.6 on 2019-12-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_progtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-level', '-level_experience'], 'verbose_name': 'profil', 'verbose_name_plural': 'profils'},
        ),
        migrations.AddField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=False, verbose_name='profil public'),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.Profile', verbose_name='profil associé'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.Profile', verbose_name='profil associé'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='adresse e-mail confirmée'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, default=';;;;;', null=True, verbose_name='liens vers les réseaux sociaux'),
        ),
    ]
