# Generated by Django 2.2.3 on 2019-08-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190804_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag_learnt',
        ),
    ]
