# Generated by Django 2.2.2 on 2019-06-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '__first__'),
        ('accounts', '0006_profile_strike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='level_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom d'utilisateur/Email Github"),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='courses.Tag', verbose_name='Compétences'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50, verbose_name="Nom de l'entreprise")),
                ('employment', models.CharField(max_length=250, verbose_name="Type d'emploi")),
                ('entry_date', models.DateField(verbose_name="Date d'entrée")),
                ('exit_date', models.DateField(auto_now_add=True, verbose_name='Date de sortie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name="Nom de l'école")),
                ('degree', models.CharField(max_length=50, verbose_name='Diplôme')),
                ('entry_date', models.DateField(verbose_name="Date d'entrée")),
                ('exit_date', models.DateField(auto_now_add=True, verbose_name='Date de sortie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
