# Generated by Django 2.2.3 on 2019-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_tag_learnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, default=';;;;;', null=True, verbose_name='liens vers les médias sociaux'),
        ),
    ]
