# Generated by Django 2.2.2 on 2019-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190614_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='exit_date',
            field=models.DateField(verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exit_date',
            field=models.DateField(verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Biographie'),
        ),
    ]
