# Generated by Django 2.2.3 on 2019-08-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190811_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['entry_date'], 'verbose_name': 'éducation', 'verbose_name_plural': 'éducations'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['entry_date'], 'verbose_name': 'expérience', 'verbose_name_plural': 'expériences'},
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.Profile', verbose_name='profile associé'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.Profile', verbose_name='profile associé'),
        ),
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('to_strike', models.BooleanField(default=False, verbose_name='à striker')),
                ('striked', models.BooleanField(default=False, verbose_name='striké')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.Profile', verbose_name='profil reporté')),
            ],
            options={
                'verbose_name': 'signalement de profil',
                'verbose_name_plural': 'signalements de profile',
            },
        ),
    ]
