# Generated by Django 2.2.3 on 2019-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190813_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_reported',
            field=models.BooleanField(default=False),
        ),
    ]
