# Generated by Django 2.2.3 on 2019-08-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_profile_reported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilereport',
            options={'verbose_name': 'signalement de profil', 'verbose_name_plural': 'signalements de profil'},
        ),
    ]
