# Generated by Django 2.2.3 on 2019-08-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('accounts', '0012_auto_20190813_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_subjects',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, null=True, to='forum.Subject', verbose_name='sujets marqués comme favoris'),
        ),
    ]
