# Generated by Django 2.2.3 on 2019-08-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190813_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, to='forum.Subject', verbose_name='sujets marqués comme favoris'),
        ),
    ]
