# Generated by Django 2.2.3 on 2019-08-19 19:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190817_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='employment',
            field=tinymce.models.HTMLField(verbose_name="type de l'emploi"),
        ),
    ]
