# Generated by Django 2.2.3 on 2019-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190827_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name="description de l'emploi"),
        ),
    ]
