# Generated by Django 2.2.6 on 2019-11-02 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titre du cours')),
                ('title_fr', models.CharField(max_length=150, null=True, verbose_name='titre du cours')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='titre du cours')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name="URL d'accès")),
                ('thumbnail', models.ImageField(upload_to='course_thumbnail/', verbose_name='vignette')),
                ('difficulty', models.CharField(choices=[('B', 'Débutant'), ('I', 'Intermédiaire'), ('E', 'Expert')], max_length=1, verbose_name='difficulté')),
                ('content_introduction', tinymce.models.HTMLField(verbose_name="contenu d'introduction")),
                ('content_introduction_fr', tinymce.models.HTMLField(null=True, verbose_name="contenu d'introduction")),
                ('content_introduction_en', tinymce.models.HTMLField(null=True, verbose_name="contenu d'introduction")),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf_course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='version PDF du cours')),
                ('published_date', models.DateField(verbose_name='date de publication')),
                ('published', models.BooleanField(default=False, verbose_name='formation publiée')),
                ('email_send', models.BooleanField(default=False, verbose_name='email envoyé')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='prix (ou ancien prix si nouveau)')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nouveau prix')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name="URL d'accès")),
                ('title', models.CharField(max_length=100, verbose_name='titre du tutoriel')),
                ('title_fr', models.CharField(max_length=100, null=True, verbose_name='titre du tutoriel')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='titre du tutoriel')),
                ('content', tinymce.models.HTMLField(verbose_name='contenu du tutoriel')),
                ('content_fr', tinymce.models.HTMLField(null=True, verbose_name='contenu du tutoriel')),
                ('content_en', tinymce.models.HTMLField(null=True, verbose_name='contenu du tutoriel')),
                ('resources', models.FileField(blank=True, null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'tar.gz', 'tar'])], verbose_name='ressources à déposer')),
                ('experience', models.PositiveSmallIntegerField(verbose_name="points d'expérience fournis")),
                ('published_date', models.DateTimeField(null=True, verbose_name='date de publication')),
                ('views', models.BigIntegerField(blank=True, default=0, verbose_name='nombre de vues')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='courses.Course', verbose_name='cours rattaché')),
            ],
            options={
                'verbose_name': 'tutoriel',
                'verbose_name_plural': 'tutoriels',
                'ordering': ['-views', 'title', 'experience'],
            },
        ),
    ]
