# Generated by Django 2.2.2 on 2019-06-19 13:52

import ckeditor.fields
import ckeditor_uploader.fields
import courses.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du cours')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnail/', verbose_name='Vignette du cours')),
                ('video_thumbnail', models.FileField(blank=True, null=True, upload_to='course_thumbnail', verbose_name="Video d'aperçu du cours")),
                ('content_introduction', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Contenu d'introduction au cours")),
                ('pdf', models.FileField(blank=True, upload_to='pdf_course/', verbose_name='Version PDF du cours')),
                ('published_date', models.DateTimeField(verbose_name='Date de publication')),
                ('old_price', courses.fields.CurrencyField(default=0, verbose_name='Prix (ou ancien prix si nouveau)')),
                ('new_price', courses.fields.CurrencyField(default=0, verbose_name='Nouveau prix')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('idea_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_of', to=settings.AUTH_USER_MODEL, verbose_name="D'après une idée de")),
                ('languages', models.ManyToManyField(blank=True, to='accounts.Language', verbose_name='Langages de programmation')),
                ('tags', models.ManyToManyField(blank=True, to='accounts.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre de la section')),
                ('short_description', ckeditor.fields.RichTextField(blank=True, max_length=450, null=True, verbose_name='Courte description de la section')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course', verbose_name='Cours attaché')),
            ],
            options={
                'verbose_name': 'Section de cours',
                'verbose_name_plural': 'Sections de cours',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title du tutoriel')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenu du tutoriel')),
                ('experience', models.PositiveSmallIntegerField(verbose_name="Points d'expérience fournis")),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Tutoriel',
                'verbose_name_plural': 'Tutoriels',
                'ordering': ['title', 'experience'],
            },
        ),
    ]
