# Generated by Django 2.2.3 on 2019-07-12 14:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du cours')),
                ('thumbnail', models.ImageField(upload_to='course_thumbnail/', verbose_name="Vignette/vidéo d'introduction")),
                ('difficulty', models.CharField(choices=[('B', 'Débutant'), ('I', 'Intermédiaire'), ('E', 'Expert')], max_length=1, verbose_name='Difficulté')),
                ('content_introduction', tinymce.models.HTMLField(verbose_name="Contenu d'introduction")),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf_course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Version PDF du cours')),
                ('published_date', models.DateField(verbose_name='Date de publication')),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Prix (ou ancien prix si nouveau)')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nouveau prix')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('languages', models.ManyToManyField(to='main.Language', verbose_name='Langages utilisés')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Étudiants enrollés')),
                ('tags', models.ManyToManyField(blank=True, to='main.Tag', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre du tutoriel')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu du tutoriel')),
                ('resources', models.FileField(blank=True, null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'tar.gz'])], verbose_name='Ressources à déposer')),
                ('experience', models.PositiveSmallIntegerField(verbose_name="Points d'expérience fournis")),
                ('published_date', models.DateTimeField(null=True, verbose_name='Date de publication')),
                ('views', models.BigIntegerField(blank=True, default=0, verbose_name='Nombre de vues')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='courses.Course', verbose_name='Cours rattaché')),
            ],
            options={
                'verbose_name': 'Tutoriel',
                'verbose_name_plural': 'Tutoriels',
                'ordering': ['-views', 'title', 'experience'],
            },
        ),
    ]
