# Generated by Django 2.2.3 on 2019-07-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-views', 'title', 'experience'], 'verbose_name': 'Tutoriel'},
        ),
    ]
