# Generated by Django 2.2.2 on 2019-06-19 15:04

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Débutant'), ('I', 'Intermédiaire'), ('E', 'Expert')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Contenu d'introduction au cours"),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(to='accounts.Language', verbose_name='Langages de programmation'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published_date',
            field=models.DateTimeField(null=True, verbose_name='Date de publication'),
        ),
    ]
