# Generated by Django 2.2.2 on 2019-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190619_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Débutant'), ('I', 'Intermédiaire'), ('E', 'Expert')], max_length=1, verbose_name='Difficulté du cours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='new_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Nouveau prix'),
        ),
        migrations.AlterField(
            model_name='course',
            name='old_price',
            field=models.FloatField(default=0, verbose_name='Prix (ou ancien prix si nouveau)'),
        ),
    ]
