# Generated by Django 2.2.3 on 2019-07-06 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20190705_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alert', models.CharField(max_length=100, verbose_name='Type du signalement')),
                ('content_alert', models.TextField(verbose_name='Contenu du signalement')),
                ('alerter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Signaleur')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courses.TutorialComment', verbose_name='Commentaire de tutoriel')),
            ],
        ),
    ]
