# Generated by Django 2.2.2 on 2019-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190619_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_date',
            field=models.DateField(verbose_name='Date de publication'),
        ),
    ]
