# Generated by Django 2.2.3 on 2019-08-01 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190727_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-views', 'title', 'experience'], 'verbose_name': 'tutoriel', 'verbose_name_plural': 'tutoriels'},
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_introduction',
            field=tinymce.models.HTMLField(verbose_name="contenu d'introduction"),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Débutant'), ('I', 'Intermédiaire'), ('E', 'Expert')], max_length=1, verbose_name='difficulté'),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(to='main.Language', verbose_name='langages utilisés'),
        ),
        migrations.AlterField(
            model_name='course',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='nouveau prix'),
        ),
        migrations.AlterField(
            model_name='course',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='prix (ou ancien prix si nouveau)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='version PDF du cours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_date',
            field=models.DateField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='étudiants enrollés'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag', verbose_name='catégories'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='course_thumbnail/', verbose_name="vignette/vidéo d'introduction"),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, verbose_name='titre du cours'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='contenu du tutoriel'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='courses.Course', verbose_name='cours rattaché'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='experience',
            field=models.PositiveSmallIntegerField(verbose_name="points d'expérience fournis"),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published_date',
            field=models.DateTimeField(null=True, verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'tar.gz'])], verbose_name='ressources à déposer'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=100, verbose_name='titre du tutoriel'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='views',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='nombre de vues'),
        ),
    ]
