# Generated by Django 2.2.2 on 2019-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190619_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='Ressources à déposer'),
        ),
    ]
