# Generated by Django 2.2.3 on 2019-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190801_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='email envoyé'),
        ),
    ]
