# Generated by Django 2.2.2 on 2019-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tutorial_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_thumbnail',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='course_thumbnail/', verbose_name='Vignette du cours'),
        ),
    ]
