# Generated by Django 2.2.2 on 2019-06-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190620_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='idea_of',
        ),
    ]
