# Generated by Django 2.2.3 on 2019-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_email_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False, verbose_name='formation publiée'),
        ),
    ]
