# Generated by Django 2.2.2 on 2019-06-21 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_idea_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='views',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf_course/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Version PDF du cours'),
        ),
    ]
