# Generated by Django 2.2.3 on 2019-08-04 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar', 'tar.gz', 'tar'])], verbose_name='ressources à déposer'),
        ),
    ]
