# Generated by Django 2.2.3 on 2019-08-19 10:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190804_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_introduction_en',
            field=tinymce.models.HTMLField(null=True, verbose_name="contenu d'introduction"),
        ),
        migrations.AddField(
            model_name='course',
            name='content_introduction_fr',
            field=tinymce.models.HTMLField(null=True, verbose_name="contenu d'introduction"),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='titre du cours'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='titre du cours'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='contenu du tutoriel'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='content_fr',
            field=tinymce.models.HTMLField(null=True, verbose_name='contenu du tutoriel'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='titre du tutoriel'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='titre du tutoriel'),
        ),
    ]
