# Generated by Django 2.2.3 on 2019-08-13 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre du sujet')),
                ('content', tinymce.models.HTMLField(verbose_name='contenu')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('closed', models.BooleanField(default=False, verbose_name='fermé')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='vues')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé')),
            ],
            options={
                'verbose_name': 'sujet',
                'verbose_name_plural': 'sujets',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='réponse')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('likes', models.PositiveSmallIntegerField(default=0, verbose_name="j'aimes")),
                ('best_answer', models.BooleanField(default=False, verbose_name='meilleure réponse')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.Subject', verbose_name='sujet associé')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé')),
            ],
            options={
                'verbose_name': 'réponse de sujet',
                'verbose_name_plural': 'réponses de sujet',
                'ordering': ['best_answer', 'likes', 'timestamp'],
            },
        ),
    ]
