# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre du sujet')),
                ('content', tinymce.models.HTMLField(verbose_name='contenu')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('closed', models.BooleanField(default=False, verbose_name='fermé')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='vues')),
            ],
            options={
                'verbose_name': 'sujet',
                'verbose_name_plural': 'sujets',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='réponse')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('best_answer', models.BooleanField(default=False, verbose_name='meilleure réponse')),
            ],
            options={
                'verbose_name': 'réponse de sujet',
                'verbose_name_plural': 'réponses de sujet',
                'ordering': ['best_answer', 'timestamp'],
            },
        ),
    ]
