# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectanswer',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name="j'aimes"),
        ),
        migrations.AddField(
            model_name='subjectanswer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.Subject', verbose_name='sujet associé'),
        ),
        migrations.AddField(
            model_name='subjectanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_answers', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé'),
        ),
        migrations.AddField(
            model_name='subject',
            name='languages',
            field=models.ManyToManyField(related_name='subject', to='main.Language', verbose_name='langages utilisés'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé'),
        ),
    ]
