# Generated by Django 2.2.3 on 2019-08-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190813_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tags',
        ),
    ]
