# Generated by Django 2.2.3 on 2019-08-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_remove_subject_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectanswer',
            options={'ordering': ['best_answer', 'timestamp'], 'verbose_name': 'réponse de sujet', 'verbose_name_plural': 'réponses de sujet'},
        ),
        migrations.RemoveField(
            model_name='subjectanswer',
            name='likes',
        ),
        migrations.AddField(
            model_name='subjectanswer',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name="j'aimes"),
        ),
        migrations.AlterField(
            model_name='subjectanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_answers', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur associé'),
        ),
    ]
