# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperienceJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.SmallIntegerField(default=0, verbose_name='expérience')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date/heure')),
            ],
            options={
                'verbose_name': "journal d'expérience utilisateur",
                'verbose_name_plural': "journaux d'expérience utilisateur",
            },
        ),
    ]
