# Generated by Django 2.2.3 on 2019-08-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexperiencejournal',
            options={'verbose_name': "journal d'expérience utilisateur", 'verbose_name_plural': "journaux d'expérience utilisateur"},
        ),
    ]
