# Generated by Django 2.2.3 on 2019-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20190805_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperiencejournal',
            name='experience',
            field=models.SmallIntegerField(default=0, verbose_name='expérience'),
        ),
    ]
