# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='nom')),
                ('discount_price', models.FloatField(verbose_name='prix déduit')),
                ('limited', models.PositiveSmallIntegerField(default=100, verbose_name='nombre de personnes qui peuvent utiliser le code')),
                ('deactivate_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date de désactivation du code')),
            ],
            options={
                'verbose_name': 'coupon promotionnel',
                'verbose_name_plural': 'coupons promotionnels',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=20, verbose_name='code de référence')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name="date de création de l'ordre d'achat")),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='date de la transaction')),
                ('ordered', models.BooleanField(default=False, verbose_name='commandé')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='demande de remboursement')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='demande de remboursement acceptée')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-ordered_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50, verbose_name='identifiant de paiement Stripe')),
                ('amount', models.FloatField(verbose_name='montant')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='date du paiement')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='raison')),
                ('refund_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='identifiant de remboursement Stripe')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepté')),
                ('rejected', models.BooleanField(default=False, verbose_name='rejeté')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'remboursement',
                'verbose_name_plural': 'remboursements',
                'ordering': ['-id'],
            },
        ),
    ]
