# Generated by Django 2.2.3 on 2019-07-27 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190715_1127'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date', '-start_date'], 'verbose_name': 'commande'},
        ),
        migrations.AddField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(to='courses.Course', verbose_name='Cours choisis'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Commandé'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de la transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de création de l'ordre d'achat"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
            preserve_default=False,
        ),
    ]
