# Generated by Django 2.2.3 on 2019-07-28 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_auto_20190727_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 27, 15, 34, 4, 786816, tzinfo=utc), null=True, verbose_name='Date de désactivation du code'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50, verbose_name='Identifiant de paiement Stripe')),
                ('amount', models.FloatField(verbose_name='Montant')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'paiement',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Payment', verbose_name='Paiement associé'),
        ),
    ]
