# Generated by Django 2.2.3 on 2019-07-28 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_auto_20190728_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('discount_price', models.FloatField(verbose_name='Prix déduit')),
                ('limited', models.PositiveSmallIntegerField(default=100, verbose_name='Nombre de personnes qui peuvent utiliser le code')),
                ('deactivate_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 27, 19, 43, 31, 148662, tzinfo=utc), null=True, verbose_name='Date de désactivation du code')),
                ('used_by', models.ManyToManyField(related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='Code utilisé par')),
            ],
            options={
                'verbose_name': 'code promotionnel',
                'verbose_name_plural': 'codes promotionnels',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='codes',
            field=models.ManyToManyField(to='billing.Coupon', verbose_name='Code de promotion attaché'),
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
