# Generated by Django 2.2.3 on 2019-07-28 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20190728_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='name',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='codes',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Coupon', verbose_name='Code de promotion attaché'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 27, 20, 1, 54, 280810, tzinfo=utc), null=True, verbose_name='Date de désactivation du code'),
        ),
    ]
