# Generated by Django 2.2.3 on 2019-07-29 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20190729_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False, verbose_name='Demande de remboursement acceptée'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='Demande de remboursement'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 28, 10, 10, 56, 72490, tzinfo=utc), null=True, verbose_name='Date de désactivation du code'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Raison')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepté')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'remboursement',
            },
        ),
    ]
