# Generated by Django 2.2.3 on 2019-07-29 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20190729_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identifiant de remboursement Stripe'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 28, 12, 29, 58, 17859, tzinfo=utc), null=True, verbose_name='Date de désactivation du code'),
        ),
    ]
