# Generated by Django 2.2.3 on 2019-07-29 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20190729_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Rejeté'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 28, 12, 48, 55, 236096, tzinfo=utc), null=True, verbose_name='Date de désactivation du code'),
        ),
    ]
