# Generated by Django 2.2.3 on 2019-08-01 09:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20190729_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date', '-start_date'], 'verbose_name': 'commande', 'verbose_name_plural': 'commandes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-id'], 'verbose_name': 'remboursement', 'verbose_name_plural': 'remboursements'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 9, 51, 17, 658923, tzinfo=utc), null=True, verbose_name='date de désactivation du code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.FloatField(verbose_name='prix déduit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limited',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='nombre de personnes qui peuvent utiliser le code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='codes', to=settings.AUTH_USER_MODEL, verbose_name='code utilisé par'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Coupon', verbose_name='code de promotion attaché'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(to='courses.Course', verbose_name='cours choisis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='commandé'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de la transaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.Payment', verbose_name='paiement associé'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(max_length=20, verbose_name='code de référence'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False, verbose_name='demande de remboursement acceptée'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='demande de remboursement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date de création de l'ordre d'achat"),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(max_length=50, verbose_name='identifiant de paiement Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date du paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepté'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Order', verbose_name='commande'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='raison'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='identifiant de remboursement Stripe'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='rejeté'),
        ),
    ]
