# Generated by Django 2.2.3 on 2019-08-01 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20190801_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 15, 14, 45, 978879, tzinfo=utc), null=True, verbose_name='date de désactivation du code'),
        ),
    ]
