# Generated by Django 2.2.3 on 2019-08-04 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20190801_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 3, 15, 35, 25, 411771, tzinfo=utc), null=True, verbose_name='date de désactivation du code'),
        ),
    ]
