# Generated by Django 2.2.3 on 2019-08-09 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_auto_20190808_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='deactivate_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 8, 15, 37, 37, 965908, tzinfo=utc), null=True, verbose_name='date de désactivation du code'),
        ),
    ]
