# Generated by Django 2.2.3 on 2019-07-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20190713_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'article")),
                ('slug', models.URLField(blank=True, null=True, verbose_name="URL d'accès")),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnail/', verbose_name="Vignette/vidéo d'article")),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('timestamp', models.DateField(verbose_name='Date de publication')),
                ('last_modification', models.DateField(verbose_name='Dernière modification')),
                ('views', models.BigIntegerField(blank=True, default=0, verbose_name='Nombre de vues')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('languages', models.ManyToManyField(to='main.Language', verbose_name='Langages utilisés')),
                ('tags', models.ManyToManyField(blank=True, to='main.Tag', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-timestamp', '-views'],
            },
        ),
    ]
