# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="titre de l'article")),
                ('title_fr', models.CharField(max_length=150, null=True, verbose_name="titre de l'article")),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name="titre de l'article")),
                ('slug', models.SlugField(blank=True, null=True, verbose_name="URL d'accès")),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnail/', verbose_name='vignette')),
                ('content', tinymce.models.HTMLField(verbose_name='contenu')),
                ('content_fr', tinymce.models.HTMLField(null=True, verbose_name='contenu')),
                ('content_en', tinymce.models.HTMLField(null=True, verbose_name='contenu')),
                ('published', models.BooleanField(default=False, verbose_name='publié')),
                ('email_send', models.BooleanField(default=False, verbose_name='emails envoyés')),
                ('timestamp', models.DateTimeField(verbose_name='date de publication')),
                ('last_modification', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('views', models.BigIntegerField(blank=True, default=0, verbose_name='nombre de vues')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-timestamp', '-views'],
            },
        ),
    ]
