# Generated by Django 2.2.3 on 2019-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-timestamp', '-views'], 'verbose_name': 'article'},
        ),
        migrations.AlterField(
            model_name='article',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='article', to='main.Language', verbose_name='Langages utilisés'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article', to='main.Tag', verbose_name='Catégories'),
        ),
    ]
