# Generated by Django 2.2.3 on 2019-08-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='email envoyé'),
        ),
    ]
