# Generated by Django 2.2.3 on 2019-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_email_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_modification',
            field=models.DateTimeField(verbose_name='dernière modification'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(verbose_name='date de publication'),
        ),
    ]
