# Generated by Django 2.2.3 on 2019-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190817_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='emails envoyés'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='publié'),
        ),
    ]
