# Generated by Django 2.2.3 on 2019-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190818_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière modification'),
        ),
    ]
