# Generated by Django 2.2.3 on 2019-08-19 13:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20190818_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='contenu'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=tinymce.models.HTMLField(null=True, verbose_name='contenu'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name="titre de l'article"),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, verbose_name="titre de l'article"),
        ),
    ]
