# Generated by Django 2.2.3 on 2019-07-20 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_auto_20190715_1127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('random_order', models.BooleanField(default=True, help_text='Afficher aléatoirement les questions ?', verbose_name='Ordre aléatoire ?')),
                ('single_attempt', models.BooleanField(default=False, verbose_name='Simple essai')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.Course')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Ordre des questions')),
                ('question_list', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Liste des questions')),
                ('incorrect_questions', models.CharField(blank=True, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Questions incorrectes')),
                ('current_score', models.IntegerField(verbose_name='Score actuel')),
                ('complete', models.BooleanField(default=False, verbose_name='Terminé')),
                ('user_answers', models.TextField(blank=True, default='{}', verbose_name="Réponses de l'utilisateur")),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Commencement')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Séance',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=1000, verbose_name='Question')),
                ('explanation', models.TextField(max_length=2000, verbose_name='Explication')),
                ('random_answer_display', models.BooleanField(default=True, help_text='Afficher les réponses dans le désordre ?', verbose_name='Ordre aléatoire ?')),
                ('quiz', models.ManyToManyField(to='polls.Quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Entrez la réponse que vous voulez afficher', max_length=450, verbose_name='Contenu')),
                ('correct', models.BooleanField(default=False, help_text='Est-ce la bonne réponse ?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse',
            },
        ),
    ]
