# Generated by Django 2.2.3 on 2019-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'réponse'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quiz'},
        ),
        migrations.AlterModelOptions(
            name='sitting',
            options={'verbose_name': 'séance'},
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Explication'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=False, verbose_name='Un seul essai'),
        ),
    ]
