# Generated by Django 2.2.3 on 2019-07-20 15:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190720_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=tinymce.models.HTMLField(help_text='Entrez la réponse que vous voulez afficher', max_length=450, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='Explication'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
