# Generated by Django 2.2.3 on 2019-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190720_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='experience',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Expérience'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='questions', to='polls.Quiz', verbose_name='Quiz'),
        ),
    ]
