# Generated by Django 2.2.3 on 2019-08-01 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190727_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'réponse', 'verbose_name_plural': 'réponses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='sitting',
            options={'verbose_name': 'séance', 'verbose_name_plural': 'séances'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=tinymce.models.HTMLField(help_text='Entrez la réponse que vous voulez afficher', max_length=450, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Est-ce la bonne réponse ?', verbose_name='correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='experience',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='expérience'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='explication'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=tinymce.models.HTMLField(max_length=1000, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='random_answer_display',
            field=models.BooleanField(default=True, help_text='Afficher les réponses dans le désordre ?', verbose_name='ordre aléatoire ?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=True, help_text='Afficher aléatoirement les questions ?', verbose_name='ordre aléatoire ?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='single_attempt',
            field=models.BooleanField(default=False, verbose_name='un seul essai'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=30, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='terminé'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='current_score',
            field=models.IntegerField(verbose_name='score actuel'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='incorrect_questions',
            field=models.CharField(blank=True, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='questions incorrectes'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_list',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='liste des questions'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_order',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='ordre des questions'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quiz', verbose_name='quiz'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='commencement'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_answers',
            field=models.TextField(blank=True, default='{}', verbose_name="réponses de l'utilisateur"),
        ),
    ]
