# Generated by Django 2.2.3 on 2019-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_initial2'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='multiple',
            field=models.BooleanField(blank=True, default=False, verbose_name='multiple sélection (checkbox)'),
        ),
    ]
