# Generated by Django 2.2.3 on 2019-08-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190822_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='multiple',
        ),
    ]
