# Generated by Django 2.2.3 on 2019-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_poll_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de votes'),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de votes'),
        ),
    ]
