# Generated by Django 2.2.3 on 2019-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='Adresse IP'),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
