# Generated by Django 2.2.6 on 2019-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191227_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='credit',
            field=models.URLField(max_length=120, null=True, verbose_name="URL vers l'image initiale"),
        ),
        migrations.AddField(
            model_name='tag',
            name='credit',
            field=models.URLField(max_length=120, null=True, verbose_name="URL vers l'image initiale"),
        ),
    ]
