# Generated by Django 2.2.3 on 2019-07-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190713_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'commentaire'},
        ),
        migrations.AlterModelOptions(
            name='commentreport',
            options={'verbose_name': 'signalement de commentaire', 'verbose_name_plural': 'signalements de commentaire'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'langage de programmation', 'verbose_name_plural': 'langages de programmation'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'catégorie'},
        ),
    ]
