# Generated by Django 2.2.6 on 2019-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191228_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='credit',
            field=models.URLField(blank=True, max_length=120, null=True, verbose_name="URL vers l'image initiale"),
        ),
        migrations.AlterField(
            model_name='tag',
            name='credit',
            field=models.URLField(blank=True, max_length=120, null=True, verbose_name="URL vers l'image initiale"),
        ),
    ]
