# Generated by Django 2.2.3 on 2019-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190715_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='striked',
            field=models.BooleanField(default=False, verbose_name='Striké'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
    ]
