# Generated by Django 2.2.6 on 2019-12-28 11:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191228_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='contenu du bandeau')),
                ('start_time', models.DateTimeField(verbose_name='date de posage du bandeau')),
                ('end_time', models.DateTimeField(verbose_name='date de fin du bandeau')),
            ],
            options={
                'verbose_name': "bandeau de la page d'accueil",
                'verbose_name_plural': "bandeaux de la page d'accueil",
            },
        ),
    ]
