# Generated by Django 2.2.3 on 2019-07-19 15:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190717_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description du langage'),
        ),
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='languages_tags/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='tag',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description de la catégorie'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='languages_tags/', verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nom de la catégorie'),
        ),
    ]
