# Generated by Django 2.2.6 on 2019-12-28 11:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_indexbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbanner',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Très petits écrans (téléphones portables) : 500px.\nPetits écrans (tablettes) : 800px.\nÉcrans moyens : 1050px.\nÉcrans larges : 1300px.\nÉcrans très larges : >1600px.', null=True, verbose_name='contenu du bandeau'),
        ),
    ]
