# Generated by Django 2.2.6 on 2019-12-28 12:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbanner',
            name='content',
            field=tinymce.models.HTMLField(help_text='Très petits écrans (téléphones portables) : 500px.\nPetits écrans (tablettes) : 800px.\nÉcrans moyens : 1050px.\nÉcrans larges : 1300px.\nÉcrans très larges : >1600px.', verbose_name='contenu du bandeau'),
        ),
    ]
