# Generated by Django 2.2.3 on 2019-07-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190719_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name="URL d'accès"),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name="URL d'accès"),
        ),
    ]
