# Generated by Django 2.2.3 on 2019-08-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190719_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'commentaire', 'verbose_name_plural': 'commentaires'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'catégorie', 'verbose_name_plural': 'catégories'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='commentaire ou réponse'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name="modèle de l'objet"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name="identifiant de l'objet"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='alerter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='signaleur'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.Comment', verbose_name='commentaire reporté'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='content_alert',
            field=models.TextField(blank=True, null=True, verbose_name='contenu du signalement'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='striked',
            field=models.BooleanField(default=False, verbose_name='striké'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='type_alert',
            field=models.CharField(choices=[('A', 'Harcèlement'), ('B', 'Discriminations physiques, racistes, sexistes'), ('C', 'Incitations ou apologie du terrorisme'), ('D', 'Incitations à la violence et à la haine'), ('E', 'Autre (explications demandées)')], max_length=1, verbose_name='type de signalement'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='vérifié'),
        ),
        migrations.AlterField(
            model_name='language',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description du langage'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='languages_tags/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom du langage de programmation'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description de la catégorie'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='languages_tags/', verbose_name='illustration'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP'),
        ),
    ]
