# Generated by Django 2.2.6 on 2019-12-28 15:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191228_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbanner',
            name='content_en',
            field=tinymce.models.HTMLField(help_text='Très petits écrans (téléphones portables) : 500px.\nPetits écrans (tablettes) : 800px.\nÉcrans moyens : 1050px.\nÉcrans larges : 1300px.\nÉcrans très larges : >1600px.', null=True, verbose_name='contenu du bandeau'),
        ),
        migrations.AddField(
            model_name='indexbanner',
            name='content_fr',
            field=tinymce.models.HTMLField(help_text='Très petits écrans (téléphones portables) : 500px.\nPetits écrans (tablettes) : 800px.\nÉcrans moyens : 1050px.\nÉcrans larges : 1300px.\nÉcrans très larges : >1600px.', null=True, verbose_name='contenu du bandeau'),
        ),
    ]
