# Generated by Django 2.2.6 on 2020-01-04 20:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191228_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbanner',
            name='content',
            field=tinymce.models.HTMLField(help_text='Très petits écrans (téléphones portables) : 500px.<br>Petits écrans (tablettes) : 800px.<br>Écrans moyens : 1050px.<br>Écrans larges : 1300px.<br>Écrans très larges : >1600px.', verbose_name='contenu du bandeau'),
        ),
        migrations.AlterField(
            model_name='indexbanner',
            name='content_en',
            field=tinymce.models.HTMLField(help_text='Très petits écrans (téléphones portables) : 500px.<br>Petits écrans (tablettes) : 800px.<br>Écrans moyens : 1050px.<br>Écrans larges : 1300px.<br>Écrans très larges : >1600px.', null=True, verbose_name='contenu du bandeau'),
        ),
        migrations.AlterField(
            model_name='indexbanner',
            name='content_fr',
            field=tinymce.models.HTMLField(help_text='Très petits écrans (téléphones portables) : 500px.<br>Petits écrans (tablettes) : 800px.<br>Écrans moyens : 1050px.<br>Écrans larges : 1300px.<br>Écrans très larges : >1600px.', null=True, verbose_name='contenu du bandeau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='natural_language',
            field=models.CharField(default='en', max_length=5, verbose_name="langage naturel de l'utilisateur"),
        ),
    ]
