# Generated by Django 2.2.3 on 2019-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190801_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False, verbose_name='reporté'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='to_strike',
            field=models.BooleanField(default=False, verbose_name='à striker'),
        ),
    ]
