# Generated by Django 2.2.3 on 2019-08-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190805_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'langage de programmation ou bibliothèque', 'verbose_name_plural': 'langages de programmation ou bibliothèques'},
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom du langage de programmation/bibliothèque'),
        ),
    ]
