# Generated by Django 2.2.3 on 2019-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190808_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='natural_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr-Fr', max_length=10),
        ),
    ]
