# Generated by Django 2.2.3 on 2019-08-19 14:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190818_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description du langage'),
        ),
        migrations.AddField(
            model_name='language',
            name='content_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description du langage'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nom du langage de programmation/bibliothèque'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nom du langage de programmation/bibliothèque'),
        ),
        migrations.AddField(
            model_name='tag',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description de la catégorie'),
        ),
        migrations.AddField(
            model_name='tag',
            name='content_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description de la catégorie'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nom de la catégorie'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nom de la catégorie'),
        ),
    ]
